name: SonarQube Analysis

on:
  push:
    branches: [ "master" ] # Or your main branch name
  pull_request:
    branches: [ "master" ] # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones not recommended for SonarQube analysis

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Replace with your .NET version

      - name: Install SonarQube scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarQube analysis
        run: dotnet-sonarscanner begin /k:"cybersimha:cybersimha_ToDoList" /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}" /o:"cybersimha" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build and test
        run: |
          dotnet build --configuration Release
          dotnet test --configuration Release

      - name: End SonarQube analysis
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}"
        
